version: '3.8'

services:
  frontend:
    image: veeru0115/taskmanager-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: veeru0115/taskmanager-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@my-postgres:5432/taskmanager
    depends_on:
      - my-postgres
    networks:
      - my-network

  my-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
